#!/usr/bin/env python3
'''
    Charts for HexCrawl

'''
# pylint: disable=E0501

from collections import namedtuple

TownTrait = namedtuple('TownTrait', ['name', 'description'])

TOWN_TRAITS = {
    11: TownTrait("Dry", "This Town has declared alcohol to be a vile sin and forbids the purchase of or the imbibing of any alcoholic demon drink. Heroes may not purchase any alcoholic Side Bag Tokens here but may attempt to sell them at the Camp Site for twice the price. When attempting to sell, roll a D6. On a 1 or 2, the sale is discovered and the Heroes must end their Town Stay and cannot enter Town for a week."),
    12: TownTrait("Dark Secret", ""),
    13: TownTrait("No Stones Allowed!", ""),
    14: TownTrait("Dark Stone Infused", ""),
    15: TownTrait("Shortages", ""),
    16: TownTrait("Obligation", ""),
    21: TownTrait("Degenerate", ""),
    22: TownTrait("Bad Water", ""),
    23: TownTrait("Inbred", ""),
    24: TownTrait("Xenophobic", ""),
    25: TownTrait("Unstable Gate", ""),
    26: TownTrait("Foreigners", ""),
    31: TownTrait("Heathens", ""),
    32: TownTrait("Cannibals!", ""),
    33: TownTrait("Religious Cult", ""),
    34: TownTrait("Boring", ""),
    35: TownTrait("Bartering", ""),
    36: TownTrait("Corrupt", ""),
    41: TownTrait("Thieving", ""),
    42: TownTrait("Slavers", ""),
    43: TownTrait("Amazonian", ""),
    44: TownTrait("Peaceful", ""),
    45: TownTrait("Addicted", ""),
    46: TownTrait("Nightmares", ""),
    51: TownTrait("Artifact Decay", ""),
    52: TownTrait("Bad Luck", ""),
    53: TownTrait("Black Market", ""),
    54: TownTrait("Jovial", ""),
    55: TownTrait("Constructive", ""),
    56: TownTrait("Cattle Yard", ""),
    61: TownTrait("Law Abiding", ""),
    62: TownTrait("Fancy House", ""),
    63: TownTrait("Unstable Economy", ""),
    64: TownTrait("Dimensional Paradox", ""),
    65: TownTrait("Well-Defended", ""),
    66: TownTrait("Unique Location", ""),

}
    # when adding to a DB table, we will want additional fields:
    #    [available, origin]
    'title',
    'keywords',
    'location',
    'time',
    'background',
    'description',
    'reward',
    'failure'
])

JOBS = {
    1: Job("job_1", [], "", 0, "", "", "", ""),
    2: Job("job_2", [], "", 0, "", "", "", ""),
    3: Job("job_3", [], "", 0, "", "", "", ""),
    4: Job("job_4", [], "", 0, "", "", "", ""),
    5: Job("job_5", [], "", 0, "", "", "", ""),
    6: Job("job_6", [], "", 0, "", "", "", ""),
    7: Job("job_7", [], "", 0, "", "", "", ""),
    8: Job("job_8", [], "", 0, "", "", "", ""),
    9: Job("job_9", [], "", 0, "", "", "", ""),
    10: Job("job_10", [], "", 0, "", "", "", ""),
    11: Job("job_11", [], "", 0, "", "", "", ""),
    12: Job("job_12", [], "", 0, "", "", "", ""),
    13: Job("job_13", [], "", 0, "", "", "", ""),
    14: Job("job_14", [], "", 0, "", "", "", ""),
    15: Job("job_15", [], "", 0, "", "", "", ""),
    16: Job("job_16", [], "", 0, "", "", "", ""),
    17: Job("job_17", [], "", 0, "", "", "", ""),
    18: Job("job_18", [], "", 0, "", "", "", ""),
    19: Job("job_19", [], "", 0, "", "", "", ""),
    20: Job("job_20", [], "", 0, "", "", "", ""),
    21: Job("job_21", [], "", 0, "", "", "", ""),
    22: Job("job_22", [], "", 0, "", "", "", ""),
    23: Job("job_23", [], "", 0, "", "", "", ""),
    24: Job("job_24", [], "", 0, "", "", "", ""),
    25: Job("job_25", [], "", 0, "", "", "", ""),
    26: Job("job_26", [], "", 0, "", "", "", ""),
    27: Job("job_27", [], "", 0, "", "", "", ""),
    28: Job("job_28", [], "", 0, "", "", "", ""),
    29: Job("job_29", [], "", 0, "", "", "", ""),
    30: Job("job_30", [], "", 0, "", "", "", ""),
    31: Job("job_31", [], "", 0, "", "", "", ""),
    32: Job("job_32", [], "", 0, "", "", "", ""),
    33: Job("job_33", [], "", 0, "", "", "", ""),
    34: Job("job_34", [], "", 0, "", "", "", ""),
    35: Job("job_35", [], "", 0, "", "", "", ""),
    36: Job("job_36", [], "", 0, "", "", "", ""),
    37: Job("job_37", [], "", 0, "", "", "", ""),
    38: Job("job_38", [], "", 0, "", "", "", ""),
    39: Job("job_39", [], "", 0, "", "", "", ""),
    40: Job("job_40", [], "", 0, "", "", "", ""),
    41: Job("job_41", [], "", 0, "", "", "", ""),
    42: Job("job_42", [], "", 0, "", "", "", ""),
    43: Job("job_43", [], "", 0, "", "", "", ""),
    44: Job("job_44", [], "", 0, "", "", "", ""),
    45: Job("job_45", [], "", 0, "", "", "", ""),
    46: Job("job_46", [], "", 0, "", "", "", ""),
    47: Job("job_47", [], "", 0, "", "", "", ""),
    48: Job("job_48", [], "", 0, "", "", "", ""),
    49: Job("job_49", [], "", 0, "", "", "", ""),
    50: Job("job_50", [], "", 0, "", "", "", ""),
    51: Job("job_51", [], "", 0, "", "", "", ""),
    52: Job("job_52", [], "", 0, "", "", "", ""),
    53: Job("job_53", [], "", 0, "", "", "", ""),
    54: Job("job_54", [], "", 0, "", "", "", ""),
    55: Job("job_55", [], "", 0, "", "", "", ""),
    56: Job("job_56", [], "", 0, "", "", "", ""),
    57: Job("job_57", [], "", 0, "", "", "", ""),
    58: Job("job_58", [], "", 0, "", "", "", ""),
    59: Job("job_59", [], "", 0, "", "", "", ""),
    60: Job("job_60", [], "", 0, "", "", "", ""),
    61: Job("job_61", [], "", 0, "", "", "", ""),
    62: Job("job_62", [], "", 0, "", "", "", ""),
    63: Job("job_63", [], "", 0, "", "", "", ""),
    64: Job("job_64", [], "", 0, "", "", "", ""),
    65: Job("job_65", [], "", 0, "", "", "", ""),
    66: Job("job_66", [], "", 0, "", "", "", ""),
    67: Job("job_67", [], "", 0, "", "", "", ""),
    68: Job("job_68", [], "", 0, "", "", "", ""),
    69: Job("job_69", [], "", 0, "", "", "", ""),
    70: Job("job_70", [], "", 0, "", "", "", ""),
    71: Job("job_71", [], "", 0, "", "", "", ""),
    72: Job("job_72", [], "", 0, "", "", "", ""),
    73: Job("job_73", [], "", 0, "", "", "", ""),
    74: Job("job_74", [], "", 0, "", "", "", ""),
    75: Job("job_75", [], "", 0, "", "", "", ""),
    76: Job("job_76", [], "", 0, "", "", "", ""),
    77: Job("job_77", [], "", 0, "", "", "", ""),
    78: Job("job_78", [], "", 0, "", "", "", ""),
    79: Job("job_79", [], "", 0, "", "", "", ""),
    80: Job("job_80", [], "", 0, "", "", "", ""),
    81: Job("job_81", [], "", 0, "", "", "", ""),
    82: Job("job_82", [], "", 0, "", "", "", ""),
    83: Job("job_83", [], "", 0, "", "", "", ""),
    84: Job("job_84", [], "", 0, "", "", "", ""),
    85: Job("job_85", [], "", 0, "", "", "", ""),
    86: Job("job_86", [], "", 0, "", "", "", ""),
    87: Job("job_87", [], "", 0, "", "", "", ""),
    88: Job("job_88", [], "", 0, "", "", "", ""),
    89: Job("job_89", [], "", 0, "", "", "", ""),
    90: Job("job_90", [], "", 0, "", "", "", ""),
    91: Job("job_91", [], "", 0, "", "", "", ""),
    92: Job("job_92", [], "", 0, "", "", "", ""),
    93: Job("job_93", [], "", 0, "", "", "", ""),
    94: Job("job_94", [], "", 0, "", "", "", ""),
    95: Job("job_95", [], "", 0, "", "", "", ""),
    96: Job("job_96", [], "", 0, "", "", "", ""),
    97: Job("job_97", [], "", 0, "", "", "", ""),
    98: Job("job_98", [], "", 0, "", "", "", ""),
    99: Job("job_99", [], "", 0, "", "", "", ""),
    100: Job("job_100", [], "", 0, "", "", "", ""),
}
